---
- name: Ensure target directory exists
  file:
    path: "{{ base16_shell_target_dir }}"
    state: directory

- name: Ensure base16-shell repo is available
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    version: master
    dest: "{{ base16_shell_repo_dir }}"

- name: Ensure selected theme is set
  file:
    src: "{{ base16_shell_repo_dir }}/scripts/base16-{{ base16_shell_theme }}.sh"
    dest: "{{ ansible_user_dir }}/.base16_theme"
    state: link
    mode: "u=rw,g=,o="
