---
- name: Ensure Docker CE is installed
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_distribution }}.yml"

- name: Create the docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add users to the docker secondary group
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Reset ssh connection to allow user changes to affect current user
  meta: reset_connection

- name: Start the docker service
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started
