---
- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rx,o="
  loop:
    - "{{ ansible_user_dir }}/.mail"
    - "{{ config_dir }}/msmtp"

- name: Ensure packages are installed
  become: true
  ansible.builtin.package:
    name:
      - isync
      - mailcap
      - msmtp
      - neomutt
      - w3m
    state: present

- name: Ensure configuration is present
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "u=r,g=r,o="
  loop:
    - src: neomuttrc
      dest: "{{ config_dir }}/neomutt/"
    - src: mailcap
      dest: "{{ ansible_user_dir }}/.mailcap"

- name: Ensure configuration is present
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "u=r,g=r,o="
  loop:
    - src: mbsyncrc
      dest: "{{ ansible_user_dir }}/.mbsyncrc"
    - src: msmtp.conf
      dest: "{{ config_dir }}/msmtp/config"

- name: Ensure Neomutt account configurations are present
  ansible.builtin.template:
    src: "accounts/{{ item }}.neomuttrc"
    dest: "{{ config_dir }}/neomutt/accounts/"
    mode: "u=r,g=r,o="
  loop:
    - gmail
    - outlook-1
    - outlook-2
    - protonmail
