---
- name: Ensure yubikey-touch-detector is installed
  become: yes
  package:
    name: yubikey-touch-detector
    state: present

- name: Ensure configuration directory exists
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure configuration is present
  copy:
    src: service.conf
    dest: "{{ config_dir }}"
    mode: "u=r,g=,o="

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: yubikey-touch-detector
    enabled: yes
    state: started
    scope: user
