---
borg_borgmatic_config:
  location:
    source_directories:
      - /home/dan/.ssh
      - /home/dan/.newsboat
      - /home/dan/docs
      - /home/dan/git
      - /home/dan/phone
      - /home/dan/tombs
    exclude_if_present:
      - .do_not_backup
    repositories:
      - "{{ lookup('community.general.passwordstore', 'borg/cloud-office/borgbase/repo') }}"

  storage:
    encryption_passcommand: pass borg/cloud-office/passphrase
    compression: none
    checkpoint_interval: 300
    extra_borg_options:
      prune: "--list -s"
      create: "--progress --list --filter=AME --stats"

  retention:
    keep_within: 3m
