---
- name: Include profile specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files: "desktop_profiles/{{ ansible_hostname }}/{{ desktop_environment_profile }}.yml"
      skip: true
  tags: desktop_environment_quick

- name: Configure components
  include_role:
    role: "{{ item }}"
  tags: always
  loop:
    - dannixon.user.nerdfont
    - i3status_rust

- name: Ensure packages are installed
  become: true
  package:
    name:
      - adobe-source-han-sans-otc-fonts
      - alacritty
      - blueman
      - feh
      - firefox
      - grim
      - jq
      - libnotify
      - light
      - mako
      - slurp
      - sway
      - swaylock
      - ttf-dejavu
      - wl-clipboard
      - wtype
      - xdg-desktop-portal-wlr
      - xdg-utils
      - xorg-xwayland
      - zathura
      - zathura-pdf-mupdf
    state: present

- name: Ensure user is in video group (required for rootless light)
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - video

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=,o="
  loop:
    - "{{ desktop_environment_applications_dir }}"
    - "{{ desktop_environment_script_dir }}"
    - "{{ desktop_environment_config_dir }}/alacritty"
    - "{{ desktop_environment_config_dir }}/mako"
    - "{{ desktop_environment_config_dir }}/sway"

- name: Ensure configuration is present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "u=r,g=,o="
  loop:
    - src: chromium-flags.conf
      dest: "{{ ansible_user_dir }}/.config/"
    - src: chromium-flags.conf
      dest: "{{ ansible_user_dir }}/.var/app/org.chromium.Chromium/config/"
    - src: chromium-flags.conf
      dest: "{{ ansible_user_dir }}/.var/app/com.github.Eloston.UngoogledChromium/config/"
    - src: mako.conf
      dest: "{{ desktop_environment_config_dir }}/mako/config"
    - src: zathura.desktop
      dest: "{{ desktop_environment_applications_dir }}/"

- name: Ensure configuration is present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "u=rw,g=,o="
  loop:
    - src: alacritty.yml.j2
      dest: "{{ desktop_environment_config_dir }}/alacritty/alacritty.yml"
    - src: sway.j2
      dest: "{{ desktop_environment_config_dir }}/sway/config"
  tags: desktop_environment_quick

- name: Update applications database
  command: update-desktop-database "{{ desktop_environment_applications_dir }}"

- name: Ensure scripts are present
  copy:
    src: scripts/
    dest: "{{ desktop_environment_script_dir }}"
    mode: "u=rx,g=,o="

- name: Ensure default applications are set
  command: xdg-mime default "{{ item.app }}" "{{ item.type }}"
  loop:
    - app: feh.desktop
      type: image/jpeg
    - app: feh.desktop
      type: image/png
    - app: feh.desktop
      type: image/webp
    - app: zathura.desktop
      type: application/pdf

- name: Reload Sway
  command: swaymsg reload
  tags:
    - never
    - desktop_environment_quick
