---
- name: Ensure infrastructure is created
  community.general.terraform:
    project_path: "{{ terraform_project_path }}"
    variables: "{{ terraform_variables }}"
    state: present
  register: terraform

- name: Build inventory
  add_host:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    ansible_user: "{{ item.user }}"
    ansible_host: "{{ item.host }}"
    ansible_ssh_common_args: "{{ '-o StrictHostKeyChecking=no' if terraform.changed else '' }}"
    ansible_ssh_private_key_file: "{{ terraform_ssh_private_key_file }}"
  loop: "{{ terraform.outputs.inventory.value }}"
