---
- name: Ensure packages are installed
  become: true
  ansible.builtin.package:
    name:
      - git
      - neovim
    state: present

- name: Ensure configuration is present
  ansible.builtin.copy:
    src: init.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/"
    mode: "u=rw,g=r,o="

- name: Ensure vim-plug is present
  ansible.builtin.copy:
    src: plug.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/autoload/"
    mode: "u=rw,g=r,o="

- name: Ensure plugins are installed and up to date
  ansible.builtin.command: nvim +PlugUpdate +exit +exit  # noqa no-changed-when

- name: Perform platform specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_os_family }}.yml"
      skip: true
