---
- name: Ensure hostname is set
  become: yes
  copy:
    dest: /etc/hostname
    content: |
      {{ hostname if hostname else inventory_hostname }}

- name: Ensure local host entries are present
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - '127.0.0.1 localhost'
    - '::1 localhost'
    - "127.0.1.1 {{ hostname if hostname else inventory_hostname }}"

- name: Ensure locale is generated
  become: yes
  community.general.locale_gen:
    name: "{{ locale }}"

- name: Ensure locale is selected
  become: yes
  copy:
    dest: /etc/locale.conf
    content: |
      LANG={{ locale }}

- name: Ensure keyboard layout is selected
  become: yes
  copy:
    dest: /etc/vconsole.conf
    content: |
      KEYMAP={{ keymap }}

- name: Ensure timezone is selected
  become: yes
  community.general.timezone:
    name: "{{ timezone }}"

- name: Ensure common tools are installed
  become: yes
  package:
    name:
      - sudo
      - iproute2
    state: present

- name: Perform platform specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_os_family }}.yml"
      skip: yes
