---
- name: Ensure MPV and dependencies are installed
  become: true
  package:
    name:
      - mpv
      - socat
      - xdg-utils
    state: present

- name: Ensure configuration is present
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/mpv/"
    mode: "u=r,g=r,o="
  loop:
    - config
    - input.conf

- name: Ensure MPV is the default viewer for GIFs
  command: xdg-mime default 'mpv.desktop' 'image/gif'  # noqa no-changed-when
