---
- name: Ensure packages are installed
  become: true
  ansible.builtin.package:
    name:
      - darktable
      - gimp
      - inkscape
      - perl-image-exiftool
      - xsane
    state: present
