---
- name: Setup akane

  hosts: localhost
  connection: local

  vars:
    profile: default

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - package_updates
    - name: system_essentials
      vars:
        hostname: akane

    - bluetooth
    - dnscrypt_proxy
    - networkmanager
    - pulseaudio
    - ufw

    - user_essentials
    - pass

    - base16_shell
    - cad_tools
    - hsxkpasswdrc
    - libreoffice
    - manpages
    - misc_scripts
    - mpd_clients
    - mpv
    - newsboat
    - sdr
    - syncthing
    - taskwarrior
    - tmux

    - general_packages

    - name: desktop_environment
      tags:
        - desktop_environment
