---
- name: Setup akane

  hosts: localhost
  connection: local

  vars:
    profile: default

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - package_updates
    - name: system_essentials
      vars:
        hostname: akane

    - bluetooth
    - dnscrypt-proxy
    - networkmanager
    - pulseaudio
    - ufw

    - user_essentials
    - pass

    - base16-shell
    - cad
    - hsxkpasswdrc
    - libreoffice
    - manpages
    - misc_scripts
    - mpd_clients
    - mpv
    - newsboat
    - sdr
    - syncthing
    - tmux
    - todotxt

    - name: desktop_environment
      tags:
        - desktop_environment

  tasks:
    - name: Install other packages
      become: yes
      package:
        name:
          - base-devel
          - borg
          - dnsutils
          - ffmpeg
          - firefox
          - go-pie
          - gpxsee
          - hugo
          - ipcalc
          - qrencode
          - sshfs
          - sshuttle
          - udevil
          - unzip
        state: present
