---
- name: Setup akane

  hosts: localhost
  connection: local

  vars:
    profile: default

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

    - name: Ensure packages are up to date
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

  roles:
    - bluetooth
    - dnscrypt-proxy
    - networkmanager
    - pulseaudio
    - ufw

    - essentials
    - pass

    - hsxkpasswdrc
    - misc_scripts
    - mpd_clients
    - mpv
    - netdata
    - newsboat
    - sdr
    - syncthing
    - tmux
    - todotxt

    - name: desktop_environment
      tags:
        - desktop_environment

  tasks:
    - name: Install other packages
      become: yes
      package:
        name:
          - base-devel
          - borg
          - blueman
          - ffmpeg
          - firefox
          - go-pie
          - gpxsee
          - hugo
          - ipcalc
          - qrencode
          - sshfs
          - sshuttle
          - udevil
          - unzip
        state: present
      tags:
        - package_installation
