---
- name: Setup akane

  hosts: localhost

  vars:
    profile: default
    system_hostname: akane

    nftables_tables:
      - table: inet filter
        includes:
          - /etc/nftables.conf.d/chain-input-default.nft
          - /etc/nftables.conf.d/chain-forward-drop.nft
          - /etc/nftables.conf.d/chain-output-accept.nft
          - /etc/nftables.conf.d/chain-input-ssh.nft
          - /etc/nftables.conf.d/chain-input-syncthing.nft
          - /etc/nftables.conf.d/chain-input-jacktrip.nft
        chains:
          input-host:
            - jump input-ssh
            - jump input-syncthing
            # - jump input-jacktrip

  pre_tasks:
    - name: Include profile specific variables
      include_vars: "vars/{{ ansible_hostname }}/{{ profile }}.yml"
      tags:
        - always

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user

    - dannixon.system.bluetooth
    - dannixon.system.networkmanager
    - dannixon.system.nftables
    - dannixon.system.dnscrypt_proxy
    - dannixon.system.sshd
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire

    - dannixon.user.base16_shell
    - dannixon.user.pass
    - dannixon.user.syncthing
    - dannixon.user.yubikey_touch_detector

    - user_essentials

    - audio_tools
    - cad_tools
    - calendar_and_contacts
    - hsxkpasswdrc
    - libreoffice
    - misc_scripts
    - mpd_clients
    - mpv
    - newsboat
    - sdr_tools
    - taskwarrior
    - tmux

    - general_packages

    - desktop_environment
