---
- name: Setup akane

  hosts: localhost
  connection: local

  vars:
    profile: default
    system_hostname: akane
    nftables_config_file: akane.nft
    interactive_user_username: dan
    interactive_user_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+vdIusbvn2f1ME6riwqwU2sfaYeRLYLkV5LAKiFHmOLHFnHtYX1DZ5YWOIlmmGfUx5azzFfxlOYjRAMn3S4JxD3/pyfYUjUJdT2rtQx1TGpI5whV24f0vTDbCxgtpgzBEsdRiQmVY+YpFbfh5hpknmBM2HBGNXZbLJe7PmIXklRNNKl2PkbB7QsVu4OnLcBKGQVRi2hcqCEtYgt9WtxuenvnAt+VHt5Gm2/n/bPFIotBUNYMoIrVjagilltn5KbyXOPNeXKyhZ5P0bYx/ejiQeCVwF3DedGjWES/cjF5LpmtAfNX01i+j13Oj9t01QZauvPUrK4tqEsApOcUt4gCcU062U5LjAgNCXL++2WUpem6y5JxpO9QqIYovsFpXsLvBPUlOHhYdcgUjKTdG5eRh96IWgu2Xo5hBvYHY11Em35tiVa3UNI4ZUKiNzOMe2D5bQkbUOjribxjcUxzpEvP4x+WIpHv9ww+5qvSkaHnnEko5gOloMd3iduKsJi/VTAFIR0L+WJadlEKIIjSOqAQVCo+yyCR2shE7n5oHTriCJ+q2HBqz6d39JBT1u/jNw7TqC42nO+yZ1BXCC3tzJLYhGrPX8AdAXbYLd2BL/9bOYuUX2D8CyvZlM0ujevudsAwsSKeFbLVqJKZ2R+/kDniU/LbojdCZsQrRSo7A1Ml0xw== dan_nixon"

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user

    - dannixon.system.bluetooth
    - dannixon.system.networkmanager
    - dannixon.system.nftables
    - dannixon.system.dnscrypt_proxy
    - dannixon.system.sshd
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - pipewire

    - user_essentials
    - pass

    - base16_shell
    - cad_tools
    - calendar_and_contacts
    - hsxkpasswdrc
    - libreoffice
    - misc_scripts
    - mpd_clients
    - mpv
    - newsboat
    - sdr_tools
    - syncthing
    - taskwarrior
    - tmux
    - yubikey_touch_detector

    - general_packages

    - name: desktop_environment
      tags:
        - desktop_environment
