---
- name: Setup akane

  hosts: localhost

  vars:
    profile: default
    system_hostname: akane
    nftables_config_file: akane.nft

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user

    - dannixon.system.bluetooth
    - dannixon.system.networkmanager
    - dannixon.system.nftables
    - dannixon.system.dnscrypt_proxy
    - dannixon.system.sshd
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire

    - user_essentials
    - pass

    - audio_tools
    - base16_shell
    - cad_tools
    - calendar_and_contacts
    - hsxkpasswdrc
    - libreoffice
    - misc_scripts
    - mpd_clients
    - mpv
    - newsboat
    - sdr_tools
    - syncthing
    - taskwarrior
    - tmux
    - yubikey_touch_detector

    - general_packages

    - desktop_environment
