#!/bin/bash

# Creates copies of GitHub repos as bundles
# Takes input from stdin in format [user]/[repo]
# e.g. cat FILE | github_export

mkdir GitBackup
cd GitBackup

while read repo
do
  git clone --mirror git@github.com:$repo.git
  IFS='/' read -a repo_details <<< "$repo"
  cd ${repo_details[1]}.git
  git bundle create ../${repo_details[1]}.bundle --all
  cd ..
  rm -r -f ${repo_details[1]}.git
  echo Backed up $repo
done
