#!/usr/bin/env bash

set -e

DOTBOT_DIR="third_party/dotbot"
DOTBOT_BIN="bin/dotbot"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

for CONFIG in ${@}; do
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" --base-directory "${BASEDIR}" --config-file "${CONFIG}"
done
