#!/usr/bin/env bash

set -e

CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="thrid_party/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIGS_DIR="configs/"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

for CONFIG in ${@}; do
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIGS_DIR}${CONFIG}${CONFIG_SUFFIX}"
done
