---
- name: Setup kawashiro
  hosts: kawashiro

  pre_tasks:
    - name: Set secrets
      ansible.builtin.set_fact:
        host_secrets: "{{ lookup('community.general.passwordstore', 'ansible_secrets/%s returnall=true' % ansible_hostname) | from_yaml }}"

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_users
    - dannixon.system.auditd

    - dannixon.system.bluetooth
    - dannixon.system.networkd
    - dannixon.system.iwd
    - dannixon.system.nftables
    - dannixon.system.tailscale
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire

    - dannixon.services.dnscrypt_proxy
    - dannixon.services.sshd

    - dannixon.user.base16_shell
    - dannixon.user.pass
    - dannixon.user.yubikey_touch_detector

    - dannixon.services.syncthing

    - dannixon.dotfiles.flatpak

    - dannixon.dotfiles.audio_tools
    - dannixon.dotfiles.cad_tools
    - dannixon.dotfiles.git
    - dannixon.dotfiles.gnupg
    - dannixon.dotfiles.hsxkpasswdrc
    - dannixon.dotfiles.libreoffice
    - dannixon.dotfiles.mpv
    - dannixon.dotfiles.neovim
    - dannixon.dotfiles.tmux
    - dannixon.dotfiles.zsh

    - dannixon.dotfiles.general_packages

    - dannixon.dotfiles.desktop_environment
