---
- name: Setup kawashiro
  hosts: kawashiro

  pre_tasks:
    - name: Set secrets
      ansible.builtin.set_fact:
        host_secrets: "{{ lookup('community.general.passwordstore', 'ansible_secrets/%s returnall=true' % ansible_hostname) | from_yaml }}"

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user
    - dannixon.system.auditd

    - dannixon.system.bluetooth
    - dannixon.system.networkd
    - dannixon.system.iwd
    - dannixon.system.nftables
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire

    - dannixon.services.dnscrypt_proxy
    - dannixon.services.sshd

    - dannixon.user.base16_shell
    - dannixon.user.pass
    - dannixon.user.yubikey_touch_detector

    - dannixon.services.syncthing

    - flatpak

    - audio_tools
    - cad_tools
    - git
    - gnupg
    - hsxkpasswdrc
    - libreoffice
    - mpv
    - neovim
    - tmux
    - zsh

    - general_packages

    - desktop_environment
