---
- name: Setup maya
  hosts: maya

  vars:
    profile: default

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user

    - dannixon.system.bluetooth
    - dannixon.system.networkmanager
    - dannixon.system.nftables
    - dannixon.system.dnscrypt_proxy
    - dannixon.system.sshd
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire
    - dannixon.system.ddcutil
    - dannixon.system.wireguard

    - dannixon.user.base16_shell
    - dannixon.user.pass
    - dannixon.user.syncthing
    - dannixon.user.yubikey_touch_detector

    - user_essentials

    - dannixon.system.mpd

    - audio_tools
    - cad_tools
    - cd_and_dvd_tools
    - email
    - gnucash
    - hsxkpasswdrc
    - libreoffice
    - misc_scripts
    - mpd_clients
    - mpv
    - newsboat
    - photo_and_image_tools
    - remote_access_tools
    - sdr_tools
    - taskwarrior
    - terraform
    - tmux

    - general_packages

    - desktop_environment

  tasks:
    - name: Ensure Bolt is installed
      become: yes
      package:
        name:
          - bolt
        state: present

    - name: Ensure Kubernetes tools are installed
      become: yes
      package:
        name:
          - kubectl
          - kubectx
          - helm
        state: present

    # - name: Ensure Packer is installed
    #   become: yes
    #   package:
    #     name:
    #       - packer
    #     state: present
