---
- name: Setup maya

  hosts: localhost
  connection: local

  vars:
    profile: default

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - package_updates
    - name: system_essentials
      vars:
        hostname: maya

    - bluetooth
    - dnscrypt-proxy
    - networkmanager
    - pulseaudio
    - ufw

    - user_essentials
    - pass

    - name: email
      tags:
        - email

    - base16_shell
    - cad
    - cd_dvd_tools
    - gdb
    - hsxkpasswdrc
    - libreoffice
    - manpages
    - misc_scripts
    - mpd
    - mpd_clients
    - mpv
    - netdata
    - newsboat
    - remote_access_clients
    - sdr
    - syncthing
    - taskwarrior
    - tmux

    - general_packages

    - name: desktop_environment
      tags:
        - desktop_environment

  tasks:
    - name: Install Bolt
      become: yes
      package:
        name:
          - bolt
        state: present

    - name: Install Kubernetes tools
      become: yes
      package:
        name:
          - kubectl
          - kubectx
          - helm
        state: present
