---
- name: Setup maya

  hosts: localhost
  connection: local

  vars:
    profile: default
    nftables_config_file: maya.nft

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - package_updates
    - name: system_essentials
      vars:
        hostname: maya

    - bluetooth
    - dnscrypt_proxy
    - networkmanager
    - nftables
    - pulseaudio

    - user_essentials
    - pass

    - name: email
      tags:
        - email

    - base16_shell
    - cad_tools
    - calendar_and_contacts
    - cd_and_dvd_tools
    - dapnet_scripts
    - gdb
    - gnucash
    - hsxkpasswdrc
    - libreoffice
    - manpages
    - misc_scripts
    - mpd
    - mpd_clients
    - mpv
    - newsboat
    - photo_and_image_tools
    - remote_access_tools
    - sdr_tools
    - syncthing
    - taskwarrior
    - terraform
    - tmux
    - yubikey_touch_detector

    - general_packages

    - name: desktop_environment
      tags:
        - desktop_environment

  tasks:
    - name: Ensure Bolt is installed
      become: yes
      package:
        name:
          - bolt
        state: present

    - name: Ensure Kubernetes tools are installed
      become: yes
      package:
        name:
          - kubectl
          - kubectx
          - helm
        state: present

    # - name: Ensure Packer is installed
    #   become: yes
    #   package:
    #     name:
    #       - packer
    #     state: present
