---
- name: Setup maya

  hosts: localhost

  vars:
    profile: default
    system_hostname: maya
    nftables_config_file: maya.nft

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user

    - dannixon.system.bluetooth
    - dannixon.system.networkmanager
    - dannixon.system.nftables
    - dannixon.system.dnscrypt_proxy
    - dannixon.system.sshd
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire
    - dannixon.system.ddcutil

    - user_essentials
    - pass

    - audio_tools
    - base16_shell
    - cad_tools
    - calendar_and_contacts
    - cd_and_dvd_tools
    - dapnet_scripts
    - email
    - gnucash
    - hsxkpasswdrc
    - libreoffice
    - misc_scripts
    - mpd
    - mpd_clients
    - mpv
    - newsboat
    - photo_and_image_tools
    - remote_access_tools
    - sdr_tools
    - syncthing
    - taskwarrior
    - terraform
    - tmux
    - yubikey_touch_detector

    - general_packages

    - desktop_environment

  tasks:
    - name: Ensure Bolt is installed
      become: yes
      package:
        name:
          - bolt
        state: present

    - name: Ensure Kubernetes tools are installed
      become: yes
      package:
        name:
          - kubectl
          - kubectx
          - helm
        state: present

    # - name: Ensure Packer is installed
    #   become: yes
    #   package:
    #     name:
    #       - packer
    #     state: present
