---
- name: Setup maya
  hosts: maya

  pre_tasks:
    - name: Set secrets
      ansible.builtin.set_fact:
        host_secrets: "{{ lookup('community.general.passwordstore', 'ansible_secrets/%s returnall=true' % ansible_hostname) | from_yaml }}"

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_users
    - dannixon.system.auditd

    - dannixon.system.bluetooth
    - dannixon.system.networkd
    - dannixon.system.iwd
    - dannixon.system.nftables
    - dannixon.system.tailscale
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire
    - dannixon.system.ddcutil

    - dannixon.services.dnscrypt_proxy
    - dannixon.services.sshd

    - dannixon.services.grafana_agent

    - dannixon.user.base16_shell
    - dannixon.user.pass
    - dannixon.user.yubikey_touch_detector

    - dannixon.services.borg
    - dannixon.services.mpd
    - dannixon.services.syncthing

    - dannixon.dotfiles.flatpak

    - dannixon.dotfiles.audio_tools
    - dannixon.dotfiles.cad_tools
    - dannixon.dotfiles.cd_and_dvd_tools
    - dannixon.dotfiles.email
    - dannixon.dotfiles.general_packages
    - dannixon.dotfiles.git
    - dannixon.dotfiles.gnucash
    - dannixon.dotfiles.gnupg
    - dannixon.dotfiles.hsxkpasswdrc
    - dannixon.dotfiles.k8s_tools
    - dannixon.dotfiles.libreoffice
    - dannixon.dotfiles.mpd_clients
    - dannixon.dotfiles.mpv
    - dannixon.dotfiles.neovim
    - dannixon.dotfiles.newsboat
    - dannixon.dotfiles.photo_and_image_tools
    - dannixon.dotfiles.remote_access_tools
    - dannixon.dotfiles.taskwarrior
    - dannixon.dotfiles.terraform
    - dannixon.dotfiles.tmux
    - dannixon.dotfiles.yt_dlp
    - dannixon.dotfiles.zsh

    - dannixon.dotfiles.desktop_environment

  tasks:
    - name: Ensure extra flatpaks are installed
      become: true
      community.general.flatpak:
        name:
          - us.zoom.Zoom
        state: present

    - name: Ensure extra packages are installed
      become: true
      ansible.builtin.package:
        name:
          - bolt
          - gpxsee
          - influx-cli
        state: present

    - name: Ensure eduroam certificate is present
      become: true
      ansible.builtin.copy:
        content: |
          {{ lookup('community.general.passwordstore', 'ansible_secrets/stfc_eduroam/cert returnall=true') }}
        dest: /etc/ssl/certs/eduroam-linux-STFC.crt
        mode: "u=r,g=r,o=r"

    - name: Ensure eduroam configuration is present
      become: true
      ansible.builtin.copy:
        content: |
          {{ lookup('community.general.passwordstore', 'ansible_secrets/stfc_eduroam/iwd_config returnall=true') }}
        dest: /var/lib/iwd/eduroam.8021x
        mode: "u=r,g=r,o="
