---
- name: Setup maya
  hosts: maya

  pre_tasks:
    - name: Set secrets
      ansible.builtin.set_fact:
        host_secrets: "{{ lookup('community.general.passwordstore', 'ansible_secrets/%s returnall=true' % ansible_hostname) | from_yaml }}"
        wireguard_secrets:
          trusted: "{{ lookup('community.general.passwordstore', 'ansible_secrets/wireguard/trusted returnall=true') | from_yaml }}"

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user
    - dannixon.system.auditd

    - dannixon.system.bluetooth
    - dannixon.system.networkd
    - dannixon.system.iwd
    - dannixon.system.nftables
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire
    - dannixon.system.ddcutil

    - dannixon.services.dnscrypt_proxy
    - dannixon.services.sshd

    - dannixon.user.base16_shell
    - dannixon.user.pass
    - dannixon.user.yubikey_touch_detector

    - dannixon.services.mpd
    - dannixon.services.syncthing

    - flatpak

    - audio_tools
    - cad_tools
    - cd_and_dvd_tools
    - email
    - general_packages
    - git
    - gnucash
    - gnupg
    - hsxkpasswdrc
    - k8s_tools
    - libreoffice
    - mpd_clients
    - mpv
    - neovim
    - newsboat
    - photo_and_image_tools
    - remote_access_tools
    - taskwarrior
    - terraform
    - tmux
    - yt_dlp
    - zsh

    - desktop_environment

  tasks:
    - name: Ensure extra flatpaks are installed
      become: yes
      flatpak:
        name:
          - com.github.Eloston.UngoogledChromium
          - com.vesc_project.VescTool
          - us.zoom.Zoom
        state: present

    - name: Ensure extra packages are installed
      become: yes
      package:
        name:
          - bolt
          - gpxsee
          # - packer
        state: present
