---
- name: Setup maya

  hosts: localhost
  connection: local

  vars:
    profile: default

  pre_tasks:
    - name: Include profile specific variables
      include_vars: 'vars/{{ ansible_hostname }}/{{ profile }}.yml'
      tags:
        - always

    - name: Ensure packages are up to date
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

  roles:
    - name: system_essentials
      vars:
        hostname: maya

    - bluetooth
    - dnscrypt-proxy
    - networkmanager
    - pulseaudio
    - ufw

    - user_essentials
    - pass

    - name: email
      tags:
        - email

    - cad
    - cd_dvd_tools
    - gdb
    - hsxkpasswdrc
    - manpages
    - misc_scripts
    - mpd
    - mpd_clients
    - mpv
    - netdata
    - newsboat
    - qemu_host
    - remote_access_client
    - sdr
    - syncthing
    - tmux
    - todotxt

    - name: desktop_environment
      tags:
        - desktop_environment

  tasks:
    - name: Install other packages
      become: yes
      package:
        name:
          - base-devel
          - bolt
          - borg
          - blueman
          - dnsutils
          - ffmpeg
          - firefox
          - go-pie
          - gpxsee
          - hugo
          - ipcalc
          - qrencode
          - rclone
          - sshfs
          - sshuttle
          - udevil
          - unzip
        state: present
