#!/bin/bash

cd

git_projects=(dotfiles IeNoTenshi UrabeVocalSynth ArduinoESCLib FutureGadget2)
svn_projects=(csc2022_team15)

function status {
  for git_proj in "${git_projects[@]}"
  do
    cd $git_proj
    echo === $git_proj
    git status
    echo
    cd
  done

  for svn_proj in "${svn_projects[@]}"
  do
    cd $svn_proj
    echo === $svn_proj
    svn status
    echo
    cd
  done
}

function update_all {
  echo Updating all version controlled projects
  echo

  for git_proj in "${git_projects[@]}"
  do
    cd $git_proj
    echo === $git_proj
    git pull
    echo
    cd
  done

  for svn_proj in "${svn_projects[@]}"
  do
    cd $svn_proj
    echo === $svn_proj
    svn update
    echo
    cd
  done
}

if [ "$1" = "update" ]
then
  update_all
  exit
fi

status
