---
- name: Setup sakuya
  hosts: sakuya

  roles:
    - dannixon.system.arch_mirrorlist
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.interactive_user

    - dannixon.system.networkd
    - dannixon.system.nftables
    - dannixon.system.inspection_tools
    - dannixon.system.manpages
    - dannixon.system.pipewire

    - dannixon.services.sshd

    - dannixon.user.base16_shell

    - git
    - gnupg
    - misc_scripts
    - mpv
    - neovim
    - tmux
    - zsh

    - general_packages

    - desktop_environment
