---
- name: Check for suitable patch
  delegate_to: localhost
  stat:
    path: '{{ patch_filename }}'
  register: patch_file_stat_result

- name: Obtain result of patching
  delegate_to: localhost
  changed_when: no
  command: patch '{{ source_filename }}' '{{ patch_filename }}' -o -
  when: patch_file_stat_result.stat.exists
  register: patched

- name: Ensure (patched) file is present
  copy:
    content: "{{ patched['stdout'] }}"
    dest: '{{ dest }}'
  when: patch_file_stat_result.stat.exists

- name: Ensure (original) file is present
  copy:
    src: '{{ source_filename }}'
    dest: '{{ dest }}'
  when: not patch_file_stat_result.stat.exists
