---
- name: Ensure package is installed
  become: true
  ansible.builtin.package:
    name: tmux
    state: present

- name: Ensure configuration is present
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ ansible_facts['env']['HOME'] }}/.tmux.conf"
    mode: "u=rw,g=,o="
