---
- name: Ensure package is installed
  become: true
  ansible.builtin.package:
    name: i3status-rust
    state: present

- name: Ensure configuration is present
  ansible.builtin.template:
    src: config.toml
    dest: "{{ ansible_user_dir }}/.config/i3status-rust/"
    mode: "u=rw,g=r,o="
  tags: desktop_environment_quick
