---
- name: Ensure Bluez is installed
  become: yes
  package:
    name:
      - bluez
      - bluez-utils

- name: Ensure Bluetooth service is enabled and started
  become: yes
  service:
    name: bluetooth
    state: started
    enabled: yes
