---
- name: Ensure virtualisation tools are installed
  become: yes
  package:
    name:
      - dnsmasq
      - ebtables
      - libvirt
      - qemu
      - virt-manager
    state: present

- name: Ensure I am in the libvirtd group
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    append: yes
    groups: libvirt

- name: Ensure libvirtd service is started
  become: yes
  service:
    name: libvirtd
    enabled: yes
    state: started
