---
- name: Ensure dependencies are installed
  become: yes
  package:
    name: python-i3ipc
    state: present

- name: Ensure script is present
  template:
    src: sway-inactive-window-transparency.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/bin/sway-inactive-window-transparency"
    mode: "u=rx,g=,o="
  tags:
    - desktop_environment_quick

- name: Ensure systemd service is present
  copy:
    src: sway-inactive-window-transparency.service
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/systemd/user"
    mode: "u=r,g=,o="

- name: Reload systemd config
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: sway-inactive-window-transparency
    enabled: yes
    state: restarted
    scope: user
  tags:
    - desktop_environment_quick
