#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOSTNAME=$(cat /etc/hostname)
I3_CONFIG=$HOME/.i3/config
I3_SBAR_CONFIG=$HOME/.i3status.conf

echo $DIR

# Main config
echo "## COMMON CONFIG\n" > $I3_CONFIG
cat ${DIR}/i3/common_config >> $I3_CONFIG

echo "## SYSTEM SPECIFIC CONFIG" >> $I3_CONFIG
if [ -e ${DIR}/i3/system_configs/$HOSTNAME ]
then
  cat ${DIR}/i3/system_configs/$HOSTNAME >> $I3_CONFIG
fi

# Status bar config
echo "## COMMON CONFIG\n" > $I3_SBAR_CONFIG
cat ${DIR}/i3status/common_config >> $I3_SBAR_CONFIG

echo "## SYSTEM SPECIFIC BAR ORDERING" >> $I3_SBAR_CONFIG
if [ -e ${DIR}/i3status/system_orders//$HOSTNAME ]
then
  cat ${DIR}/i3status/system_orders/$HOSTNAME >> $I3_SBAR_CONFIG
else
  cat ${DIR}/i3status/system_orders/default >> $I3_SBAR_CONFIG
fi
