#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOSTNAME=$(cat /etc/hostname)
I3_CONFIG_DIR=$HOME/.i3
I3_CONFIG=$I3_CONFIG_DIR/config

mkdir -p $I3_CONFIG_DIR

# Main config
echo "## COMMON CONFIG\n" > $I3_CONFIG
cat ${DIR}/common_config >> $I3_CONFIG

echo "## SYSTEM SPECIFIC CONFIG" >> $I3_CONFIG
if [ -e ${DIR}/system_configs/$HOSTNAME ]
then
  cat ${DIR}/system_configs/$HOSTNAME >> $I3_CONFIG
fi
