#!/bin/bash

THEME="base16-black-metal"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOSTNAME=$(cat /etc/hostname)

# Make config directory
I3_CONFIG_DIR=${HOME}/.i3
mkdir -p ${I3_CONFIG_DIR}

# Config filename
I3_CONFIG=${I3_CONFIG_DIR}/config

# Add the theme and common config
THEME_CONFIG_FILE=${DIR}/base16-i3/colors/${THEME}.config
COMMON_CONFIG_FILE=${DIR}/common_config
cat ${THEME_CONFIG_FILE} ${COMMON_CONFIG_FILE} > ${I3_CONFIG}

# Add the system specific config if it exists
SYSTEM_CONFIG_FILE=${DIR}/system_configs/${HOSTNAME}
if [ -e ${SYSTEM_CONFIG_FILE} ]
then
  cat ${SYSTEM_CONFIG_FILE} >> ${I3_CONFIG}
fi
