---
dircolors_configs:
  - terminal:
      - "*"
    config:
      RESET: 00
      DIR: 00;34
      LINK: 00;36
      MULTIHARDLINK: 00
      FIFO: 40;33
      SOCK: 00;35
      DOOR: 00;35
      BLK: 40;33;01
      CHR: 40;33;01
      ORPHAN: 40;31;01
      MISSING: 00
      SETUID: 37;41
      SETGID: 30;43
      CAPABILITY: 30;41
      STICKY_OTHER_WRITABLE: 30;42
      OTHER_WRITABLE: 34;42
      STICKY: 37;44
      EXEC: 00;32
    files:
      - name: Archive formats
        color: 00;31
        match:
          - .tar
          - .tgz
          - .arc
          - .arj
          - .taz
          - .lha
          - .lz4
          - .lzh
          - .lzma
          - .tlz
          - .txz
          - .tzo
          - .t7z
          - .zip
          - .z
          - .dz
          - .gz
          - .lrz
          - .lz
          - .lzo
          - .xz
          - .zst
          - .tzst
          - .bz2
          - .bz
          - .tbz
          - .tbz2
          - .tz
          - .deb
          - .rpm
          - .jar
          - .war
          - .ear
          - .sar
          - .rar
          - .alz
          - .ace
          - .zoo
          - .cpio
          - .7z
          - .rz
          - .cab
          - .wim
          - .swm
          - .dwm
          - .esd
      - name: Image/video formats
        color: 00;35
        match:
          - .jpg
          - .jpeg
          - .mjpg
          - .mjpeg
          - .gif
          - .bmp
          - .pbm
          - .pgm
          - .ppm
          - .tga
          - .xbm
          - .xpm
          - .tif
          - .tiff
          - .png
          - .svg
          - .svgz
          - .mng
          - .pcx
          - .mov
          - .mpg
          - .mpeg
          - .m2v
          - .mkv
          - .webm
          - .ogm
          - .mp4
          - .m4v
          - .mp4v
          - .vob
          - .qt
          - .nuv
          - .wmv
          - .asf
          - .rm
          - .rmvb
          - .flc
          - .avi
          - .fli
          - .flv
          - .gl
          - .dl
          - .xcf
          - .xwd
          - .yuv
          - .cgm
          - .emf
          - .ogv
          - .ogx
      - name: Audio formats
        color: 00;36
        match:
          - .aac
          - .au
          - .flac
          - .m4a
          - .mid
          - .midi
          - .mka
          - .mp3
          - .mpc
          - .ogg
          - .ra
          - .wav
          - .oga
          - .opus
          - .spx
          - .xspf
