---
- name: Ensure prerequisites are installed
  become: yes
  package:
    name:
      - fontconfig
      - unzip
    state: present

- name: Ensure font directory exists
  file:
    path: "{{ font_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure font files are available
  unarchive:
    src: "{{ archive_url }}"
    dest: "{{ font_dir }}"
    remote_src: yes

- name: Rebuild font cache
  command: fc-cache --force --verbose
  when: rebuild_cache|bool
