---
- name: Ensure font directory exists
  file:
    path: '{{ font_dir }}'
    state: directory

- name: Ensure font files are available
  unarchive:
    src: '{{ archive_url }}'
    dest: '{{ font_dir }}'
    remote_src: yes

- name: Rebuild font cache
  changed_when: no
  command: fc-cache --force --verbose
  when: rebuild_cache|bool
