---
- name: Ensure feh is installed
  become: yes
  package:
    name:
      - feh
      - xdg-utils
    state: present

- name: Ensure feh is the default viewer for appropriate formats
  command: xdg-mime default 'feh.desktop' '{{ item }}'
  loop:
    - 'image/jpeg'
    - 'image/png'
    - 'image/webp'
