---
- name: Ensure packages are installed
  become: yes
  package:
    name:
      - task
      - taskwarrior-tui
    state: present

- name: Ensure configuration is present
  copy:
    src: taskrc
    dest: "{{ ansible_user_dir }}/.taskrc"
