---
- name: Ensure smart card tools are installed
  become: true
  ansible.builtin.package:
    name:
      - ccid
      - pcsclite
      - yubikey-manager
      - yubikey-personalization
    state: present
