---
- name: Ensure GnuPG is installed
  become: true
  ansible.builtin.package:
    name: gnupg
    state: present

- name: Ensure configuration is present
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.gnupg/"
    mode: "u=r,g=,o="
  loop:
    - gpg.conf
    - gpg-agent.conf

- name: Ensure my public key is present
  ansible.builtin.shell:  # noqa no-changed-when
    cmd: curl 'https://dan-nixon.com/pubkey.txt' | gpg --import -
    warn: false

- name: Perform platform specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_os_family }}.yml"
      skip: true
