---
grafana_agent_config:
  integrations:
    agent:
      enabled: true
    node_exporter:
      enabled: true

  server:
    log_level: info

  metrics:
    wal_directory: /var/lib/grafana-agent
    global:
      scrape_interval: 1m
      remote_write:
        - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
          basic_auth:
            username: "{{ host_secrets.grafana_agent.prometheus_username }}"
            password: "{{ host_secrets.grafana_agent.token }}"
          write_relabel_configs:
            - source_labels:
                - __name__
              regex: "up|node_(cpu.*|disk.*|filesystem.*|hwmon.*|load.*|memory.*|network.*|pressure.*|power_supply.*)"
              action: keep
    configs:
      - name: default
        scrape_configs:
          - job_name: agent
            static_configs:
              - targets:
                  - 127.0.0.1:12345
