---
networkd_config:
  20-wired:
    network:
      Match:
        Type: ether
      Network:
        DHCP: "yes"
      DHCP:
        RouteMetric: 10

  20-wireless:
    network:
      Match:
        Type: wlan
      Network:
        DHCP: "yes"
      DHCP:
        RouteMetric: 20
