---
desktop_environment_displays:
  - name: LVDS-1
    enabled: true

i3status_rust_blocks:
  - block: sound
    device_kind: sink

  - block: sound
    device_kind: source

  - block: time
    interval: 1
    format: " $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S')"
