---
- name: Ensure Zsh is installed
  become: yes
  package:
    name: zsh
    state: present

- name: Ensure Zsh configuration is present
  template:
    src: zshrc.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    mode: "u=rw,g=,o="
    block_start_string: "{<<"
    block_end_string: ">>}"

- name: Ensure Zsh is set at the user's logon shell
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
