---
- name: Ensure Zsh is installed
  become: yes
  package:
    name: zsh
    state: present

- name: Ensure Zsh configuration is present
  template:
    src: zshrc.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    mode: "u=rw,g=,o="
    block_start_string: "{<<"
    block_end_string: ">>}"

- name: Ensure Zsh is set at the user's logon shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Ensure fzf completion tool is present
  git:
    repo: https://github.com/lincheney/fzf-tab-completion
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/fzf-tab-completion"
  when: zsh_fzf_completion

- name: Ensure fzf is installed
  become: yes
  package:
    name: fzf
    state: present
  when: zsh_fzf_completion
