---
- name: Ensure Zsh is installed
  package:
    name: zsh
    state: present
  tags:
    - package_installation

- name: Ensure Zsh configuration is present
  copy:
    src: 'zshrc'
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
