---
- name: Ensure Zsh is installed
  become: yes
  package:
    name: zsh
    state: present
  tags:
    - package_installation

- name: Ensure Zsh configuration is present
  copy:
    src: 'zshrc'
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"

- name: Ensure Zsh is set at the user's logon shell
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
