---
- name: Ensure Git is installed
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Ensure configuration is present
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/git/"
    mode: "u=r,g=,o="
  loop:
    - attributes
    - config
    - ignore

- name: Ensure gfold is installed
  become: true
  ansible.builtin.package:
    name: gfold
    state: present
  when: ansible_os_family == "Archlinux"
