---
- name: Ensure the user exists
  become: yes
  user:
    name: "{{ username }}"
    state: present

- name: Ensure SSH public key is present
  become: yes
  ansible.posix.authorized_key:
    user: "{{ username }}"
    key: "{{ ssh_key }}"
    state: present

- name: Ensure user can sudo if allowed
  become: yes
  copy:
    dest: "/etc/sudoers.d/{{ username }}"
    content: |
      {{ username }} ALL=(ALL) ALL
  when: sudoer

- name: Ensure the user's password is set
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    state: present
  when: password | default(no)
