---
- name: Ensure pass is installed
  become: yes
  package:
    name:
      - pass
      - pass-otp
    state: present

- name: Ensure script directory exists
  file:
    path: "{{ script_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure scripts are present
  copy:
    src: scripts/
    dest: "{{ script_dir }}"
    mode: "u=rx,g=,o="
