---
- name: Install pass and extensions
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "install_{{ ansible_distribution }}.yml"

- name: Ensure helper script is present
  become: yes
  copy:
    src: fzf.bash
    dest: /usr/lib/password-store/extensions/fzf.bash
    mode: "u=rx,g=rx,o=rx"
