---
- name: Ensure UFW is installed
  become: yes
  package:
    name: ufw
    state: present

- name: Ensure UFW firewall is enabled with default reject rule
  become: yes
  ufw:
    state: enabled
    default: reject

- name: Ensure UFW firewall allows retry limited SSH
  become: yes
  ufw:
    rule: limit
    to_port: ssh

- name: Ensure UFW firewall serivce is enabled and running
  become: yes
  service:
    name: ufw
    state: started
    enabled: yes
