---
- name: Ensure Git is installed
  become: yes
  package:
    name: git
    state: present

- name: Ensure Git configuration is present
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/.{{ item }}"
  loop:
    - gitconfig
    - gitignore
