---
- name: Ensure Git is installed
  become: yes
  package:
    name: git
    state: present

- name: Ensure config directory exists
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure Git configuration is present
  copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/{{ item }}"
  loop:
    - config
    - ignore
