---
- name: Ensure Git is installed
  become: yes
  package:
    name: git
    state: present

- name: Ensure config directory exists
  file:
    path: "{{ git_config_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure configuration is present
  copy:
    src: "{{ item }}"
    dest: "{{ git_config_dir }}/{{ item }}"
    mode: "u=r,g=,o="
  loop:
    - attributes
    - config
    - ignore
