---
- name: Ensure Git is installed
  become: true
  package:
    name: git
    state: present

- name: Ensure configuration is present
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/git/"
    mode: "u=r,g=,o="
  loop:
    - attributes
    - config
    - ignore
