#!/bin/bash

case "$1" in
  "sink")
    default=$(pactl info | grep 'Default Sink' | awk '{print $3}')
    ;;
  "source")
    default=$(pactl info | grep 'Default Source' | awk '{print $3}')
    ;;
  *)
    exit 1
    ;;
esac

case "$2" in
  "volume")
    pactl "set-$1-volume" "$default" "$3"
    ;;
  "mute")
    pactl "set-$1-mute" "$default" "$3"
    ;;
  *)
    exit 1
    ;;
esac
