---
- name: Ensure packages are installed
  become: true
  package:
    name:
      - mpc
      - ncmpcpp
    state: present

- name: Ensure configuration is present
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/ncmpcpp/"
    mode: "u=rw,g=r,o="
  loop:
    - "ncmpcpp/bindings"
    - "ncmpcpp/config"
