---
- name: Ensure packages are installed
  become: true
  package:
    name:
      - mpc
      - ncmpcpp
    state: present

- name: Ensure configuration directory exists
  file:
    path: "{{ config_dir }}"
    state: directory

- name: Ensure configuration is present
  copy:
    src: ncmpcpp/
    dest: "{{ config_dir }}"
