#!/bin/bash

if command -v wofi > /dev/null; then
  result=$(echo -e 'no\nyes' | wofi --dmenu --insensitive --prompt "$1")
else
  result=$(echo -e 'no\nyes' | rofi -dmenu -i -p "$1")
fi

case "$result" in
  "yes")
    echo 'y'
    ;;
  *)
    exit 1
    ;;
esac
