#!/bin/bash

set -e

_confirm() {
  result=$(echo -e 'no\nyes' | fzf --prompt="$1 ")
  case "$result" in
    "yes")
      ;;
    *)
      exit 1
      ;;
  esac
}

if [ $# -eq 1 ]; then
  action="$1"
else
  action=$(echo -e 'lock\nsleep\nshutdown\nreboot' | fzf --prompt='power/lock> ')
fi

case "$action" in
  "lock")
    swaylock --color 002030 && echo "Welcome back!"
    ;;
  "sleep")
    sync && swaylock --color 002030 --daemonize && systemctl suspend && echo "Welcome back!"
    ;;
  "shutdown")
    _confirm 'shutdown now?' && sync && poweroff
    ;;
  "reboot")
    _confirm 'reboot now?' && sync && reboot
    ;;
  *)
    exit 1
    ;;
esac
