#!/bin/bash

default_sink=$(pactl info | grep 'Default Sink' | awk '{print $3}')

case "$1" in
  "v")
    pactl set-sink-volume "$default_sink" "$2"
    ;;
  "m")
    pactl set-sink-mute "$default_sink" "$2"
    ;;
  *)
    exit 1
    ;;
esac
