#!/bin/bash

display_name="$(swaymsg -t get_outputs | jq -r '.[] | select(.focused==true) | .name')"
state_file="/tmp/sway-mouse-$WAYLAND_DISPLAY-$display_name"

display_width="$(swaymsg -t get_outputs | jq -r '.[] | select(.focused==true) | .rect.width')"
display_height="$(swaymsg -t get_outputs | jq -r '.[] | select(.focused==true) | .rect.height')"

_start() {
  rm -f "$state_file"
  let "current_x_pos = display_width / 2"
  let "current_y_pos = display_height / 2"
  let "current_x_step = display_width / 4"
  let "current_y_step = display_height / 4"
}

_finish() {
  rm -f "$state_file"
  exit
}

_click() {
  swaymsg -- seat - cursor press "$1"
  sleep 0.05
  swaymsg -- seat - cursor release "$1"
}

if [ -f "$state_file" ]; then
  current_x_pos="$(jq -r '.position.x' < "$state_file")"
  current_y_pos="$(jq -r '.position.y' < "$state_file")"
  current_x_step="$(jq -r '.step.x' < "$state_file")"
  current_y_step="$(jq -r '.step.y' < "$state_file")"
else
  _start
fi

case "$1" in
  "state")
    if [ -f "$state_file" ]; then
      cat "$state_file"
      exit
    else
      exit 1
    fi
    ;;
  "start")
    _start
    ;;
  "finish")
    _finish
    ;;
  "left_click")
    _click button1
    _finish
    ;;
  "right_click")
    _click button3
    _finish
    ;;
  "right")
    let "current_x_pos += current_x_step"
    let "current_x_step /= 2"
    ;;
  "left")
    let "current_x_pos -= current_x_step"
    let "current_x_step /= 2"
    ;;
  "up")
    let "current_y_pos -= current_y_step"
    let "current_y_step /= 2"
    ;;
  "down")
    let "current_y_pos += current_y_step"
    let "current_y_step /= 2"
    ;;
  *)
    exit 1
    ;;
esac

cat > "$state_file" <<EOF
{
  "position": {
    "x": $current_x_pos,
    "y": $current_y_pos
  },
  "step": {
    "x": $current_x_step,
    "y": $current_y_step
  }
}
EOF

swaymsg -- seat - cursor set "$current_x_pos" "$current_y_pos"
