galaxy_info:
  author: Dan Nixon
  description: Enables Wake on Lan for a given interface
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Debian
    - name: Ubuntu

dependencies: []
