---
- name: Ensure packages are installed
  become: true
  package:
    name:
      - gnuradio
      - gnuradio-companion
      - gnuradio-osmosdr
      - gqrx
      - qwt
      - rtl-sdr
    state: present
