---
- name: Ensure Neomutt and dependencies are installed
  become: yes
  package:
    name:
      - mailcap
      - neomutt
      - w3m
    state: present

- name: Ensure Neomutt configuration directories exist
  file:
    path: "{{ config_dir }}/accounts/"
    state: directory

- name: Ensure configuration is present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: neomuttrc
      dest: "{{ config_dir }}/neomuttrc"
    - src: mailcap
      dest: "{{ ansible_facts['env']['HOME'] }}/.mailcap"

- name: Ensure Neomutt account configurations are present
  include_role:
    name: copy_secret_injected_file
  vars:
    src: "accounts/{{ item }}.neomuttrc"
    dest: "{{ config_dir }}/accounts/{{ item }}.neomuttrc"
    mode: "u=r,g=r,o="
  loop:
    - gmail
    - outlook-1
    - outlook-2
    - protonmail
