---
- name: Ensure requirements for building packages are satisfied
  become: yes
  package:
    name: base-devel
    state: present

- name: Ensure a user exists to build packages
  become: yes
  user:
    name: aur_builder
    group: wheel

- name: Ensure the AUR builder user can use sudo without a password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Ensure paru is installed
  become: yes
  become_user: aur_builder
  aur:
    name: paru
    state: present
  when: aur_builder_install_paru
