---
- name: Inject secrets
  delegate_to: localhost
  changed_when: no
  shell: |
    contents="$(cat {{ source_filename }})"

    # Find everything that matches "<< pass something >>" and replace it with the value of something from pass
    for password in $(perl -ne 'while(/<< pass ([\w\/]+) >>/g){print "$1\n";}' "{{ source_filename }}" | sort --unique); do
      contents=$(echo "$contents" | pw="$(pass "$password")" perl -pe 's{<< pass '"$password"' >>}{$ENV{pw}}')
    done

    echo "$contents"
  register: inject_secrets

- name: Ensure file exists
  copy:
    content: "{{ inject_secrets['stdout'] }}"
    dest: '{{ dest }}'
