---
- name: Ensure Zathura is installed
  become: yes
  package:
    name:
      - xdg-utils
      - zathura
      - zathura-pdf-mupdf
    state: present

- name: Ensure applications configuration directory exists
  file:
    path: '{{ applications_dir }}'
    state: directory

- name: Ensure Zathura applicaton file is present
  copy:
    src: 'zathura.desktop'
    dest: '{{ applications_dir }}/zathura.desktop'

- name: Update applications database
  command: update-desktop-database "{{ ansible_facts['env']['HOME'] }}/.local/share/applications"

- name: Ensure Zathura is the default viewer for appropriate formats
  command: xdg-mime default 'zathura.desktop' 'application/pdf'
