---
- name: Ensure Terraform is installed
  become: true
  ansible.builtin.package:
    name: terraform
    state: present

- name: Ensure configuration is present
  ansible.builtin.copy:
    src: terraformrc
    dest: "{{ ansible_user_dir }}/.terraformrc"
    mode: "u=rw,g=r,o="

- name: Ensure plugin cache directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.terraform.d/plugin-cache"
    state: directory
    mode: "u=rwx,g=rx,o="
