---
- name: Ensure Terraform is installed
  become: yes
  package:
    name: terraform
    state: present

- name: Ensure configuration is present
  copy:
    src: terraformrc
    dest: "{{ ansible_user_dir }}/.terraformrc"

- name: Ensure plugin cache directory exists
  file:
    path: "{{ ansible_user_dir }}/.terraform.d/plugin-cache"
    state: directory
