---
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.mail"
    - "{{ config_dir }}/msmtp/"
    - "{{ config_dir }}/neomutt/"
    - "{{ config_dir }}/neomutt/accounts/"

- name: Ensure packages are installed
  become: yes
  package:
    name:
      - isync
      - mailcap
      - msmtp
      - neomutt
      - w3m
    state: present

- name: Ensure configuration is present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "u=r,g=r,o="
  loop:
    - src: neomuttrc
      dest: "{{ config_dir }}/neomuttrc"
    - src: mailcap
      dest: "{{ ansible_user_dir }}/.mailcap"

- name: Ensure configuration is present
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    mode: "u=r,g=r,o="
  loop:
    - src: mbsyncrc
      dest: "{{ ansible_user_dir }}/.mbsyncrc"
    - src: msmtp.conf
      dest: "{{ config_dir }}/msmtp/config"

- name: Ensure Neomutt account configurations are present
  template:
    src: "accounts/{{ item }}.neomuttrc.j2"
    dest: "{{ config_dir }}/neomutt/accounts/{{ item }}.neomuttrc"
    mode: "u=r,g=r,o="
  loop:
    - gmail
    - outlook-1
    - outlook-2
    - protonmail
