galaxy_info:
  author: Dan Nixon
  description: Installs WireGuard and configures a connection
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Ubuntu

dependencies: []
