#!/bin/bash

installed_file="$1"
original_file="$2"

patch_target="${3:-$HOSTNAME}"

patch_filename="$original_file.$patch_target.patch"

diff "$original_file" "$installed_file" > "$patch_filename"

# Check if the patch actually has any changes
if [ ! -s "$patch_filename" ]; then
  echo "Created patch was empty so was not kept"
  rm "$patch_filename"
  exit 1
fi
