#!/bin/bash

label="$1"
filename_timestamp=$(date +'%Y-%m-%d_%H-%M-%S')

if [ -n "$label" ];
then
  filename="${filename_timestamp}_${label}.txt"
else
  filename="${filename_timestamp}.txt"
fi

touch "$filename"

{ date; echo; echo; } >> "$filename"
$EDITOR "$filename"
{ echo; date; } >> "$filename"

echo "$filename"
