---
- name: Ensure target directory exists
  file:
    path: '{{ target_dir }}'
    state: directory

- name: Ensure base16-shell repo is available
  git:
    repo: 'https://github.com/chriskempson/base16-shell.git'
    dest: '{{ target_dir }}/base16-shell'
