---
- name: Ensure nftables userland tools are installed
  become: yes
  package:
    name:
      - nftables
      - iptables-nft
    state: present

- name: Ensure iptables services are disabled and stopped
  become: yes
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - iptables
    - ip6tables
