galaxy_info:
  author: Dan Nixon
  description: Performs an infrastructure deployment with Terraform and appends to the inventory
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux

dependencies: []
