- link:
    ~/.config/omf:
        create: true
        path: dotfiles/omf

- shell:
    -
        command: chsh -s /usr/bin/fish
        stdin: true
        stdout: true
        stderr: true
    -
        command: curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
        stdin: true
        stdout: true
        stderr: true
    -
        command: echo "set -Ux EDITOR nvim" | fish
        stdin: true
        stdout: true
        stderr: true
    -
        command: echo "set -Ux TODOTXT_DEFAULT_ACTION ls" | fish
        stdin: true
        stdout: true
        stderr: true
