- link:
    ~/.config/omf:
        create: true
        path: dotfiles/omf/

- shell:
    -
        command: chsh -s /usr/bin/fish
        stdin: true
        stdout: true
        stderr: true
    -
        command: sudo apt install curl python-pip python3-pip
        stdin: true
        stdout: true
        stderr: true
    -
        command: sudo pip3 install thefuck
        stdin: true
        stdout: true
        stderr: true
    -
        command: sudo pip install virtualfish
        stdin: true
        stdout: true
        stderr: true
    - "./fonts/install.sh"
    -
        command: curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
        stdin: true
        stdout: true
        stderr: true
