- link:
    ~/.config/fish:
        create: true
        path: dotfiles/fish/

- shell:
    -
        command: chsh -s /usr/bin/fish
        stdin: true
        stdout: true
        stderr: true
    -
        sudo pip install thefuck
        command: chsh -s /usr/bin/fish
        stdin: true
        stdout: true
        stderr: true
    - "./fonts/install.sh"
    - "curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish"
