- clean: ['~']

- link:
    ~/.config/terminator:
        create: true
        path: dotfiles/terminator/

    ~/.vim:
        path: dotfiles/vim/

    ~/.vimrc:
        path: dotfiles/vimrc

    ~/.direnvrc:
        path: dotfiles/direnvrc

    ~/.gitconfig:
        path: dotfiles/gitconfig

    ~/.gitignore:
        path: dotfiles/gitignore

    ~/.putty/sessions:
        create: true
        path: dotfiles/putty_serial_sessions/

    ~/.screenrc:
        path: dotfiles/screenrc

    ~/.bash_history:
        path: /dev/null

    ~/.bash_aliases:
        path: dotfiles/shell/bash_aliases

    ~/.gntrc:
        path: dotfiles/gntrc

    ~/.gnupg/dirmngr.conf:
        create: true
        path: dotfiles/gnupg/dirmngr.conf

    ~/.gnupg/gpg.conf:
        create: true
        path: dotfiles/gnupg/gpg.conf

    ~/.elinks:
        path: dotfiles/elinks

    ~/.todo:
        path: dotfiles/todo

    ~/.todo.actions.d:
        path: dotfiles/todo_actions

- shell:
    - [git submodule update --init --recursive, Installing submodules]
