---
- name: Ensure Waybar is installed
  package:
    name: waybar
    state: present

- name: Ensure Waybar configuration directory exists
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure Waybar configuration is present
  template:
    src: config.j2
    dest: "{{ config_dir }}/config"
    mode: "u=r,g=,o="
  tags:
    - desktop_environment_quick

- name: Ensure Waybar style is present
  copy:
    src: style.css
    dest: "{{ config_dir }}/style.css"
    mode: "u=r,g=,o="
