---
- name: Ensure Waybar is installed
  package:
    name: waybar
    state: present

- name: Ensure Waybar configuration directory exists
  file:
    path: '{{ config_dir }}'
    state: directory

- name: Ensure Waybar configuration is present
  template:
    src: config.j2
    dest: '{{ config_dir }}/config'
  tags:
    - desktop_environment_quick

- name: Ensure Waybar style is present
  copy:
    src: style.css
    dest: '{{ config_dir }}/style.css'
