---
galaxy_info:
  author: Dan Nixon
  description: Installs and configures software that provides touch needed notifications for YubiKeys
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux

dependencies: []
