---
- name: Ensure Newsboat is installed
  become: true
  ansible.builtin.package:
    name: newsboat
    state: present

- name: Ensure configuration is present
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_user_dir }}/.newsboat/"
    mode: "u=r,g=r,o="
