#!/bin/bash

# Exit after the first non-zero return code
set -e

src="$1"
dest="$2"

# Encrypt file (to the default recipient) and output in new location
gpg --encrypt --output "$dest" "$src"

# Securely remove original file
shred -u "$src"
