#!/bin/bash

set -e

device='sysfs/leds/dell::kbd_backlight'

function level_to_string {
  case "$1" in
    "0.00")
      echo 'off'
      ;;
    "50.00")
      echo 'dim'
      ;;
    "100.00")
      echo 'bright'
      ;;
  esac
}

function string_to_level {
  case "$1" in
    "off" | "o" )
      echo '0'
      ;;
    "dim" | "d" )
      echo '50'
      ;;
    "bright" | "b" )
      echo '100'
      ;;
  esac
}

function next_level_string {
  case "$1" in
    "off")
      echo 'bright'
      ;;
    "dim")
      echo 'off'
      ;;
    "bright")
      echo 'dim'
      ;;
  esac
}

function get_backlight {
  level_to_string "$(light -s "$device")"
}

function set_backlight {
  light -s "$device" -S "$(string_to_level "$1")"
}

if [ "$#" -ne 0 ]; then
  case "$1" in
    "toggle" | "t" )
      set_backlight "$(next_level_string "$(get_backlight)")"
      ;;
    *)
      set_backlight "$1"
      ;;
  esac
fi

get_backlight
