#!/bin/bash

# Somewhat hacky tool to automatically encrypt new files that appear in a
# directory.

src="$1"
dest="$2"
filename_regex="$3"

inotifywait --quiet --monitor --event close_write  --format '%f' "$src" | while read f; do
  src_filename="$src/$f"
  dest_filename="$dest/$f.gpg"

  if [[ "$src_filename" =~ $filename_regex ]]; then
    if [ -e "$src_filename" ]; then
      echo "\"$src_filename\" has appeared, will be encrypted to \"$dest_filename\""

      sleep 1
      atomic-gpg-encrypt-move "$src_filename" "$dest_filename"
    fi
  fi
done
