#!/bin/bash

function _usage {
  program=`basename $0`

  printf "$program: helper script for launching Dockerized Firefox instances.\n\n"
  printf "Usage:\n"
  printf "\t$program start NAME   Starts a new or existing container\n"
  printf "\t$program stop NAME    Stops a running container\n"
  printf "\t$program web NAME     Retireves the URL to access the container via a web browser\n"
  printf "\t$program open NAME    Opens the result of $program web in a private Firefox window\n"
  printf "\t$program vnc NAME     Opens a VNC session to a given container in Vinagre\n"
}

function _bad_args {
  _usage
  exit 1
}

function _start_container {
  docker run \
    --detach \
    --rm \
    --name "firefox_$1" \
    --publish "127.0.0.1::5800" \
    --publish "127.0.0.1::5900" \
    --volume "firefox_data_$1:/config:rw" \
    --shm-size 2g \
    jlesage/firefox
}


function _web_url {
  info=`docker inspect $1`
  result=$?
  if [ $result -eq 0 ]; then
    port=`echo "$info" | jq -r '.[0].NetworkSettings.Ports["5800/tcp"][0].HostPort'`
    url="http://127.0.0.1:$port"
    echo "$url"
  else
    exit $result
  fi
}


function _web_open {
  url=`_web_url $1`
  result=$?
  if [ $result -eq 0 ]; then
    firefox --private-window "$url"
  else
    exit $result
  fi
}


function _vnc_url {
  info=`docker inspect $1`
  result=$?
  if [ $result -eq 0 ]; then
    port=`echo "$info" | jq -r '.[0].NetworkSettings.Ports["5900/tcp"][0].HostPort'`
    url="127.0.0.1:$port"
    vinagre "$url"
  else
    exit $result
  fi
}


if [ ! $# -eq 2 ]; then
  _bad_args
fi

case $1 in
  start)
    _start_container $2
    ;;
  stop)
    docker stop "firefox_$2"
    ;;
  web)
    _web_url "firefox_$2"
    ;;
  open)
    _web_open "firefox_$2"
    ;;
  vnc)
    _vnc_url "firefox_$2"
    ;;
  *)
    _bad_args
esac
