#!/bin/bash

PROGRAM=$(basename "$0")

CONTAINER_PREFIX="${PROGRAM}-"
VOLUME_PREFIX="${PROGRAM}-data-"

function _usage {
  printf "%s: helper script for launching Dockerized Firefox instances.\n\n" "$PROGRAM"
  printf "Usage:\n"
  printf "\t%s ls           List existing volumes created with %s\n" "$PROGRAM" "$PROGRAM"
  printf "\t%s ls           List running containers created with %s\n" "$PROGRAM" "$PROGRAM"
  printf "\t%s start NAME   Starts a new or existing container\n" "$PROGRAM"
  printf "\t%s stop NAME    Stops a running container\n" "$PROGRAM"
  printf "\t%s web NAME     Retireves the URL to access the container via a web browser\n" "$PROGRAM"
  printf "\t%s open NAME    Opens the result of %s web in a private Firefox window\n" "$PROGRAM" "$PROGRAM"
  printf "\t%s vnc NAME     Opens a VNC session to a given container in Vinagre\n" "$PROGRAM"
}

function _bad_args {
  _usage
  exit 1
}

function _start_container {
  docker run \
    --detach \
    --rm \
    --name "$CONTAINER_PREFIX$1" \
    --publish "127.0.0.1::5800" \
    --publish "127.0.0.1::5900" \
    --volume "$VOLUME_PREFIX$1:/config:rw" \
    --shm-size 2g \
    jlesage/firefox
}


function _web_url {
  info=$(docker inspect "$1")
  result=$?
  if [ $result -eq 0 ]; then
    port=$(echo "$info" | jq -r '.[0].NetworkSettings.Ports["5800/tcp"][0].HostPort')
    url="http://127.0.0.1:$port"
    echo "$url"
  else
    exit $result
  fi
}


function _web_open {
  url=$(_web_url "$1")
  result=$?
  if [ $result -eq 0 ]; then
    firefox --private-window "$url"
  else
    exit $result
  fi
}


function _vnc_url {
  info=$(docker inspect "$1")
  result=$?
  if [ $result -eq 0 ]; then
    port=$(echo "$info" | jq -r '.[0].NetworkSettings.Ports["5900/tcp"][0].HostPort')
    url="127.0.0.1:$port"
    vinagre "$url"
  else
    exit $result
  fi
}

case "$1" in
  ls)
    if [ ! $# -eq 1 ]; then
      _bad_args
    fi
    docker volume ls --format="{{.Name}}" | grep "$VOLUME_PREFIX" | sed -e "s/$VOLUME_PREFIX//g"
    ;;
  ps)
    if [ ! $# -eq 1 ]; then
      _bad_args
    fi
    docker ps --format="{{.Names}}" | grep "$CONTAINER_PREFIX" | sed -e "s/$CONTAINER_PREFIX//g"
    ;;
  start)
    if [ ! $# -eq 2 ]; then
      _bad_args
    fi
    _start_container "$2"
    ;;
  stop)
    if [ ! $# -eq 2 ]; then
      _bad_args
    fi
    docker stop "$CONTAINER_PREFIX$2"
    ;;
  web)
    if [ ! $# -eq 2 ]; then
      _bad_args
    fi
    _web_url "$CONTAINER_PREFIX$2"
    ;;
  open)
    if [ ! $# -eq 2 ]; then
      _bad_args
    fi
    _web_open "$CONTAINER_PREFIX$2"
    ;;
  vnc)
    if [ ! $# -eq 2 ]; then
      _bad_args
    fi
    _vnc_url "$CONTAINER_PREFIX$2"
    ;;
  *)
    _bad_args
esac
