#!/bin/bash

shell="$1"

while read -r line
do
  alias="$(echo "$line" | cut -d$'\t' -f 1)"
  expansion="$(echo "$line" | cut -d$'\t' -f 2)"

  case "$shell" in
    "bash")
      echo "alias $alias=\"$expansion\""
      ;;
    "fish_abbr")
      echo "abbr --add --global $alias \"$expansion\""
      ;;
    *)
      echo "Unknown shell \"$shell\""
      exit 1
  esac
done
