#!/bin/bash

len="$1"

if [ -x "$(command -v pwgen)" ]; then
  pwgen --symbols --secure $len 1
else
  # Fall back on a manual method if pwgen is not available
  </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c $len ; echo
fi
