#!/bin/bash

# Updates each Git repo with a clean working copy
# or the current directory if it is a repo.

function update_repo {
  if [[ $(git status --porcelain) ]]
  then
    echo -e '\E[31mWorking copy not clean.'
    tput sgr0
  else
    git pull
  fi
}

if [ -d ".git" ]
then
  update_repo
else
  for dir in `ls -d */`
  do
    cd "$dir"
    if [ -d ".git" ]
    then
      echo -e "\033[1m=== $dir ===\033[0m"
      update_repo
      echo
    fi
    cd ..
  done
fi
