#!/bin/bash

# Prints status for each Git repo in the current directory
# or for the current directory if it is a repo.

function recursive_search {
  if [ -d "$1/.git" ]
  then
    cd "$1"
    if [ "$(git status --porcelain)" != "" ] || [ "$2" = "all" ]
    then
      echo -e "\033[1m=== $1 ===\033[0m"
      git status --short --branch
      echo
    fi
    cd - 1>&- 2>&-
  else
    for dir in "$1"/*
    do
      if [ -d "$dir" ]
      then
        recursive_search "$dir" "$2"
      fi
    done
  fi
}


mode="all"

while getopts ":c" opt; do
  case $opt in
    c)
      mode="c"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

root_dir=${@:$OPTIND:1}
root_dir="${root_dir:-.}"

recursive_search $root_dir $mode
