#!/bin/bash

set -eo pipefail

C_RED='\033[0;31m'
C_GREEN='\033[0;32m'
C_YELLOW='\033[0;33m'
C_CYAN='\033[0;36m'
C_NONE='\033[0m'

function usage {
  program=$(basename "$0")
  echo 'Export histpry of multiple states from a HomeAssistant instance.'
  echo "Usage: $program [from date] [to date]"
}

if [ "$#" -ne 2 ]; then
  usage
  exit 1
fi

# Always export in UTC
date_from="$1T00:00:00+00:00"
date_to="$2T23:59:59+00:00"

while read entity_id
do
  printf "${C_YELLOW}Entity \"${C_CYAN}${entity_id}${C_YELLOW}\"${C_NONE}\n"
  filename="${entity_id}_${date_from}_${date_to}.tsv"

  if [ ! -f "$filename" ]
  then
    printf "${C_GREEN}Saving to ${filename}${C_NONE}\n"
    ha-history-export \
      --time-from "$date_from" \
      --time-to "$date_to" \
      "$entity_id" > "$filename"
    chmod -w "$filename"
  else
    printf "${C_RED}Already exists: ${filename}\n"
  fi
done
