#!/usr/bin/python

# TODO: use max page size, add auth

import string
import requests
import link_header

api_endpoint = string.Template('https://api.github.com/users/$user/starred')
api_url = api_endpoint.substitute(user='dannixon')

def get_request(url, results):
    data = requests.get(api_url)
    results.extend(data.json())

    link_data = link_header.parse(data.headers['Link'])
    next_url = link_data.links_by_attr_pairs([['rel', 'next']])[0].href

    get_request(next_url, results)

repos = []
get_request(api_url, repos)

for r in repos:
    print(r['clone_url'])
