#!/bin/bash

git clone git@github.com:mantidproject/mantid.git "$1"
mkdir "$1"-build
cd "$1"-build
cmake ../"$1"/Code/Mantid -DCMAKE_BUILD_TYPE=Debug -DMANTID_DATA_STORE=~/MantidExternalData
make StandardTestData
make -j8
