#!/bin/sh

set -e

function secrets_available {
  # Checks if password-store (pass) is available
  command -v pass >/dev/null 2>&1
}

function get_secret {
  if $(secrets_available); then
    # Grab the secret from pass
    pass "$1"
  else
    # Just return an empty string if secrets are unavailable
    echo
  fi
}

filename="$1"

# Warn if we cannot inject secrets
if ! $(secrets_available); then
  echo "Secrets are not available"
  exit 1
fi

# Find everything that matches "<< pass something >>" and replace it with the value of something from pass
for password in $(perl -ne 'while(/<< pass ([\w\/]+) >>/g){print "$1\n";}' "$filename" | sort --unique); do
  echo "Inject secret ${password}"
  pw="$(get_secret "$password")" perl -pe 's{<< pass '"$password"' >>}{$ENV{pw}}' -i "$filename"
done
