#!/bin/bash

if [ $# -eq 1 ]; then
  action="$1"
else
  action=$(echo -e 'lock\nsleep\nshutdown\nreboot' | rofi -dmenu -i -p 'power/lock')
fi

case "$action" in
  "lock")
    i3lock --color 002030
    ;;
  "sleep")
    sync && i3lock --color 002030 && systemctl suspend
    ;;
  "shutdown")
    confirm-de 'shutdown now?' && sync && poweroff
    ;;
  "reboot")
    confirm-de 'reboot now?' && sync && reboot
    ;;
  *)
    exit 1
    ;;
esac
