#!/bin/bash

# Create a new random MAC address for a given interface
# May not work on all NICs

# Usage ./random-mac [interface_name]


# Get the correct interface
if [ $# -gt 0 ]
then
  interface=$1
else
  interface='wlan0'
fi
echo Operating on interface: $interface

# Generate a new MAC address
new_mac=$(printf '00:60:2F:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
echo Random new MAC address: $new_mac

# Take the interface down, apply the new MAC address, bring it back up
sudo ifconfig $interface down
sudo ifconfig $interface hw ether $new_mac
sudo ifconfig $interface up

# Show interface details
ifconfig $interface
