#!/bin/bash

notify-send --urgency=low 'youtube-dl' 'Getting formats...'

formats=$(youtube-dl -F "$1")
status="$?"

if [ "$status" -eq 0 ]; then
  echo "$formats" | sed -n '6,50p' | rofi -dmenu -i -p 'quality' | awk '{print $1}'
else
  notify-send --urgency=critical 'youtube-dl' 'Failed to get formats!'
  exit "$status"
fi
