#!/bin/bash

set -xe

# See https://stackoverflow.com/questions/6174220/parse-url-in-shell-script/45977232#45977232
# Following regex is based on https://tools.ietf.org/html/rfc3986#appendix-B with
# additional sub-expressions to split authority into userinfo, host and port
readonly URI_REGEX='^(([^:/?#]+):)?(//((([^:/?#]+)@)?([^:/?#]+)(:([0-9]+))?))?(/([^?#]*))(\?([^#]*))?(#(.*))?'
#                    ↑↑            ↑  ↑↑↑            ↑         ↑ ↑            ↑ ↑        ↑  ↑        ↑ ↑
#                    |2 scheme     |  ||6 userinfo   7 host    | 9 port       | 11 rpath |  13 query | 15 fragment
#                    1 scheme:     |  |5 userinfo@             8 :…           10 path    12 ?…       14 #…
#                                  |  4 authority
#                                  3 //…

parse_host () {
  [[ "$@" =~ $URI_REGEX ]] && echo "${BASH_REMATCH[7]}"
}

url="$1"
output_filename="rtsp_$(parse_host "$url")_$(date '+%Y-%m-%d_%H-%M-%S').avi"

ffmpeg \
  -i "$url" \
  -vcodec copy \
  -y "$output_filename"
