#!/bin/bash

cd

dotfiles/install_packages/install_packages -P dotfiles/install_packages/packages_vim

rm .vimrc
rm -r .vim

ln -s dotfiles/vimrc .vimrc
ln -s dotfiles/vim .vim

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle && vim +BundleInstall! +BundleClean +qall
