#!/bin/bash

cd

rm .vimrc
rm -r .vim

ln -s dotfiles/.vimrc .vimrc
ln -s dotfiles/.vim .vim

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle && vim +BundleInstall! +BundleClean +qall
