#!/bin/bash

# Helper function to extract data from JSON
function __jq_get {
  echo "$1" | jq -r "$2"
}

# If no location is provided obtain one from the current IP address
location_query="$1"
if [ -z "$location_query" ];
then
  resp="$(curl --silent 'http://ip-api.com/json/?fields=lat,lon')"
  location_query="$(echo $resp | jq '.lat'),$(echo $resp | jq '.lon')"
fi

# Get the forecast data
forecast=$(curl --silent "https://api.darksky.net/forecast/$DARKSKY_API_KEY/$location_query?lang=en&units=uk2")

# Helper function to extract data from the forecast JSON
function __forecast_get {
  __jq_get "$forecast" "$1"
}

# Map icon descriptions to Nerd Font icons
function __icon {
  case "$1" in
    "clear-day")
      echo ""
      ;;
    "clear-night")
      echo ""
      ;;
    "rain")
      echo ""
      ;;
    "snow")
      echo ""
      ;;
    "sleet")
      echo ""
      ;;
    "wind")
      echo ""
      ;;
    "fog")
      echo ""
      ;;
    "cloudy")
      echo ""
      ;;
    "partly-cloudy-day")
      echo ""
      ;;
    "partly-cloudy-night")
      echo ""
      ;;
  esac
}

printf "%s  %s\n" \
  "$(__icon $(__forecast_get '.currently.icon'))" \
  "$(__forecast_get '.currently.summary')"

printf "   %.1f 糖\n" \
  "$(__forecast_get '.currently.temperature')"

printf "   %.0f %%\n" \
  "$(echo "$(__forecast_get '.currently.humidity') * 100" | bc)"

printf "   %.1f (%.1f) mph\n" \
  "$(__forecast_get '.currently.windSpeed')" \
  "$(__forecast_get '.currently.windGust')"

printf "%s  %s\n" \
  "$(__icon $(__forecast_get '.minutely.icon'))" \
  "$(__forecast_get '.minutely.summary')"
