#!/bin/bash

T_DATE=$(env TZ="$1" date "+%a %e %b %Y")
T_TIME=$(env TZ="$1" date "+%T")
T_ZONE=$(env TZ="$1" date "+%Z")
T_OFFSET=$(env TZ="$1" date "+(UTC%z)")

C_GREEN='\033[0;32m'
C_YELLOW='\033[0;33m'
C_BLUE='\033[0;34m'
C_CYAN='\033[0;36m'
C_NONE='\033[0m'

printf "${C_YELLOW}${T_DATE} ${C_GREEN}${T_TIME} ${C_CYAN}${T_ZONE} ${C_BLUE}${T_OFFSET}${C_NONE}\n"
