#!/bin/sh
xrandr --output VIRTUAL1 --off --output DP1 --off --output DVI-D-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI2 --off --output HDMI-1 --off --output DVI-I-1 --off --output VGA1 --off
