#!/bin/sh
xrandr --output DP-7 --off --output DP-6 --off --output DP-5 --mode 1920x1080 --pos 1080x456 --rotate normal --output DP-4 --off --output DP-3 --off --output DP-2 --off --output DP-1 --off --output DP-0 --primary --mode 1920x1080 --pos 0x0 --rotate left
