#!/usr/bin/env python3

from bs4 import BeautifulSoup
import os
import requests
import sys
from urllib.parse import urlparse


def get_canonical_url(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')

    for l in soup.findAll(['link']):
        if 'canonical' in l.attrs.get('rel', []):
            return l['href']

    return None


def get_channel_id(url):
    p = urlparse(url)
    return os.path.split(p.path)[-1]


i = get_channel_id(get_canonical_url(sys.argv[1]))
print('https://www.youtube.com/feeds/videos.xml?channel_id={}'.format(i))
