#!/bin/bash

set -xe

url="$(xclip -o)"

format="$(rofi-youtube-dl-select-format "$url")"

notify-send --urgency=low 'youtube-dl' 'Starting download...'

youtube-dl --format="$format" "$url" \
  && notify-send 'youtube-dl' 'Download complete.' \
  || notify-send --urgency=critical 'youtube-dl' 'Download failed!'
