---
- name: Ensure dependencies are installed
  become: true
  ansible.builtin.package:
    name:
      - bash
      - fzf
      - sed
      - tmux
      - yt-dlp
    state: present

- name: Ensure scripts are present
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/bin
    mode: "u=rx,g=rx,o=rx"
  loop:
    - yt-dlp-background
    - yt-dlp-select-format
