---
- name: Ensure Sway is installed
  package:
    name:
      - sway
      - swaylock
    state: present

- name: Ensure Sway configuration directory exists
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure Sway configuration is present
  template:
    src: config.j2
    dest: "{{ config_dir }}/config"
    mode: "u=r,g=,o="
  tags:
    - desktop_environment_quick

- name: Reload Sway
  command: swaymsg reload
  when: sway_reload|bool
  tags:
    - desktop_environment_quick
