---
- name: Ensure Sway is installed
  package:
    name:
      - sway
      - swaylock
    state: present

- name: Ensure Sway configuration directory exists
  file:
    path: '{{ config_dir }}'
    state: directory

- name: Ensure Sway configuration is present
  template:
    src: config.j2
    dest: '{{ config_dir }}/config'
  tags:
    - desktop_environment_quick

- name: Reload Sway
  command: swaymsg reload
  when: sway_reload|bool
  tags:
    - desktop_environment_quick
