#!/bin/bash

NAME=$1
MON_IDX=$2
CLASS=$3
SENSOR_IDX=$4

ICON=$(echo "$CLASS" | sed -e 's:^fan$::' -e 's:^temp$:糖:')

cat <<EOF
\${color1}$NAME $ICON \${color}\${hwmon $MON_IDX $CLASS $SENSOR_IDX}
EOF
