---
- name: Ensure PipeWire and friends are installed
  become: yes
  package:
    name:
      - carla
      - jackmeter
      - jack_mixer
      - njconnect
      - patchmatrix
      - pipewire
      - pipewire-jack
      - pipewire-pulse
      - pulseeffects
      - pulsemixer
      - qjackctl

- name: Ensure services are enabled and running
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop:
    - pipewire
    - pipewire-pulse

- name: Ensure PipeWire is loaded as JACK library
  become: yes
  copy:
    src: pipewire-jack.conf
    dest: /etc/ld.so.conf.d/pipewire-jack.conf
    mode: u=rw,g=r,o=r
