---
- name: Ensure Todo.txt is installed
  become: yes
  copy:
    src: 'todo.sh'
    dest: '/usr/local/bin/todo.sh'
    mode: '+rx'

- name: Ensure Todo.txt configuration directories exist
  file:
    path: '{{ config_dir }}/actions'
    state: directory

- name: Ensure Todo.txt configuration is present
  copy:
    src: 'config'
    dest: '{{ config_dir }}/config'

- name: Ensure Todo.txt action scripts are present
  copy:
    src: 'actions/'
    dest: '{{ config_dir }}/actions/'
