---
- name: Ensure Alacritty is installed
  become: yes
  package:
    name: alacritty
    state: present

- name: Ensure Alacritty configuration directory exists
  file:
    path: '{{ config_dir }}'
    state: directory

- name: Ensure Alacritty configuration is present
  template:
    src: alacritty.yml.j2
    dest: '{{ config_dir }}/alacritty.yml'
  tags:
    - desktop_environment_quick
