---
- name: Ensure Alacritty is installed
  become: yes
  package:
    name: alacritty
    state: present
  tags:
    - package_installation

- name: Ensure Alacritty configuration directory exists
  file:
    path: '{{ config_dir }}'
    state: directory

- name: Ensure Alacritty configuration is present
  copy:
    src: 'alacritty.yml'
    dest: '{{ config_dir }}/alacritty.yml'
