#!/bin/bash

prompt="password-store"
if [ -n "$1" ]; then
  prompt="$prompt $1"
fi

if command -v wofi > /dev/null; then
  chooser="wofi --dmenu --insensitive --prompt"
else
  chooser="rofi -dmenu -i -p"
fi

find "$HOME/.password-store/" \
  -name "*.gpg" \
  -printf "%P\n" \
| sed -e "s/\.gpg//g" \
| $chooser "$prompt"
