---
- name: Mirror list URL
  debug:
    var: mirrorlist_url

- name: Create temporary file
  ansible.builtin.tempfile:
    state: file
  register: tempfile
  changed_when: no

- name: Download mirror list
  get_url:
    url: "{{ mirrorlist_url }}"
    dest: "{{ tempfile.path }}"
  changed_when: no

- name: Enable all servers in downloaded mirror list
  replace:
    path: "{{ tempfile.path }}"
    regexp: "^#Server"
    replace: "Server"
  changed_when: no

- name: Ensure mirror list is up to date
  become: yes
  copy:
    src: "{{ tempfile.path }}"
    dest: /etc/pacman.d/mirrorlist
    mode: "u=rw,g=r,o=r"

- name: Delete temporary file
  file:
    path: "{{ tempfile.path }}"
    state: absent
  changed_when: no
