---
- name: Ensure GDB is installed
  become: yes
  package:
    name: gdb
    state: present

- name: Ensure GDB configuration is present
  copy:
    src: 'gdbinit'
    dest: "{{ ansible_facts['env']['HOME'] }}/.gdbinit"
