---
galaxy_info:
  author: Dan Nixon
  description: Installs and configures email software
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux

dependencies:
  - role: gnupg
  - role: pass

  - role: mbsync
  - role: msmtp
  - role: neomutt
