---
- name: Ensure Syncthing APT key is added
  become: yes
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure Syncthing APT repository is added
  become: yes
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
  when: ansible_os_family == 'Debian'

- name: Update APT repos
  become: yes
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Ensure Syncthing is installed
  become: yes
  package:
    name: syncthing
    state: present

- name: Ensure a UFW firewall rule exists allowing Syncthing sync traffic
  become: yes
  ufw:
    rule: allow
    name: syncthing

- name: Ensure the Syncthing service is enabled and running for the target user
  become: yes
  service:
    name: 'syncthing@{{ ansible_user_id }}'
    state: started
    enabled: yes
  when: service|bool
