#!/bin/sh

I3_CONFIG=~/.i3/config
HOSTNAME=$(cat /etc/hostname)

echo "## COMMON CONFIG\n" > $I3_CONFIG
cat common_config >> $I3_CONFIG

echo "\n\n## SYSTEM SPECIFIC CONFIG\n" >> $I3_CONFIG
cat system_configs/$HOSTNAME >> $I3_CONFIG
