---
- name: Ensure essential tools are installed
  become: yes
  package:
    name:
      - htop
      - jq
      - net-tools
      - nnn
      - progress
      - rsync
      - tree
    state: present
  tags:
    - package_installation
