---
- name: Ensure Neovim is installed
  become: yes
  package:
    name: neovim
    state: present
  tags:
    - package_installation

- name: Ensure Neovim configuration directory exists
  file:
    path: '{{ config_dir }}'
    state: directory

- name: Ensure Neovim configuration is present
  copy:
    src: 'nvim/'
    dest: '{{ config_dir }}'

- name: Ensure NeoVim plugins are installed and up to date
  command: nvim +PlugUpdate +exit +exit
