---
- name: Ensure Neovim is installed
  become: yes
  package:
    name: neovim
    state: present

- name: Ensure configuration directory exists
  file:
    path: "{{ neovim_config_dir }}"
    state: directory

- name: Ensure configuration is present
  copy:
    src: nvim/
    dest: "{{ neovim_config_dir }}"

- name: Ensure plugins are installed and up to date
  command: nvim +PlugUpdate +exit +exit

- name: Perform platform specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_os_family }}.yml"
      skip: yes
