---
- name: Ensure Newsboat is installed
  become: true
  package:
    name: newsboat
    state: present

- name: Ensure configuration is present
  copy:
    src: config
    dest: "{{ ansible_user_dir }}/.newsboat/"
    mode: "u=r,g=r,o="
