---
- name: Ensure Newsboat is installed
  become: true
  package:
    name: newsboat
    state: present

- name: Ensure configuration directory exists
  file:
    path: '{{ config_dir }}'
    state: directory

- name: Ensure configuration is present
  copy:
    src: 'config'
    dest: '{{ config_dir }}/config'
