---
- name: Ensure WireGuard tools are installed
  become: yes
  package:
    name: wireguard-tools
    state: present

- name: Ensure WireGuard configuration is present and up to date
  become: yes
  notify:
    - Restart WireGuard service
  template:
    src: wg.conf.j2
    dest: '/etc/wireguard/{{ config }}.conf'

- name: Ensure the WireGuard service is enabled and started
  become: yes
  when: service
  service:
    name: 'wg-quick@{{ config }}'
    state: started
    enabled: yes
