---
- name: Ensure configuration is present
  become: yes
  copy:
    src: "{{ networkd_config_dir }}/"
    dest: /usr/lib/systemd/network
    mode: "u=rw,g=r,o=r"
  when: networkd_config_dir | d(no)
  notify:
    - Reload systemd-networkd configuration

- name: Ensure systemd-networkd is enabled and running
  become: yes
  service:
    name: systemd-networkd
    state: started
    enabled: yes
