#!/bin/bash

# Add new APT repositories
cat apt_repos | while read repo
do
  sudo apt-add-repository "$repo"
done

# Update package list and upgrade installed packages
sudo apt-get update
sudo apt-get upgrade

# Install new packages
packages=`cat apt_packages | tr '\n' ' '`
sudo apt-get install $packages
