---
- name: Ensure Mako is installed
  become: yes
  package:
    name: mako
    state: present

- name: Ensure Mako configuration directory exists
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure Mako configuration is present
  copy:
    src: config
    dest: "{{ config_dir }}/config"
    mode: "u=r,g=,o="
