---
- name: Ensure CAD/EDA packages are installed
  become: yes
  package:
    name:
      - kicad
      - librecad
      - openscad
      - prusa-slicer
    state: present
  tags:
    - package_installation

- name: Ensure DXFs open in LibreCAD
  command: xdg-mime default 'librecad.desktop' 'application/x-dxf'
